# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2017-09-09 12:05
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('playundercover', '0003_auto_20170907_2006'),
    ]

    operations = [
        migrations.CreateModel(
            name='CustomUser',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
        ),
        migrations.RemoveField(
            model_name='namelist',
            name='user',
        ),
        migrations.RemoveField(
            model_name='userpair',
            name='user',
        ),
        migrations.DeleteModel(
            name='User',
        ),
        migrations.AddField(
            model_name='customuser',
            name='user',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='namelist',
            name='custom_user',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='playundercover.CustomUser'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='userpair',
            name='custom_user',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='playundercover.CustomUser'),
            preserve_default=False,
        ),
    ]
