# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2017-09-12 13:59
from __future__ import unicode_literals

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('playundercover', '0006_pairfeedback'),
    ]

    operations = [
        migrations.AddField(
            model_name='pairfeedback',
            name='datetime',
            field=models.DateField(default=datetime.datetime(2017, 9, 12, 21, 58, 50, 734000)),
        ),
    ]
