# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2017-09-12 14:01
from __future__ import unicode_literals

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('playundercover', '0007_pairfeedback_datetime'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pairfeedback',
            name='datetime',
            field=models.DateTimeField(default=datetime.datetime(2017, 9, 12, 14, 1, 32, 230000, tzinfo=utc)),
        ),
    ]
