# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2017-09-12 14:20
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('playundercover', '0010_auto_20170912_2218'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pairfeedback',
            name='pair',
            field=models.CharField(max_length=83),
        ),
    ]
